[workspace]
authors = ["Koji Matsumoto <otomustam.ijok@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "pegra"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = "mojo test -I . test"

[dependencies]
modular = ">=25.5.0.dev2025062305,<26"
